# Generated by Django 5.0.3 on 2024-03-21 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='travelers',
            fields=[
                ('booking_id', models.IntegerField(primary_key=True, serialize=False)),
                ('passenger_1_name', models.CharField(max_length=100)),
                ('passenger_1_age', models.IntegerField()),
                ('passenger_1_email', models.CharField(max_length=100)),
                ('passenger_2_name', models.CharField(blank=True, max_length=100, null=True)),
                ('passenger_2_age', models.IntegerField(blank=True, null=True)),
                ('passenger_2_email', models.CharField(blank=True, max_length=100, null=True)),
                ('card_number', models.IntegerField()),
            ],
            options={
                'db_table': 'travelers',
            },
        ),
    ]
