# Generated by Django 5.0.3 on 2024-03-23 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelers', '0002_alter_travelers_card_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='states',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'state',
            },
        ),
    ]
