# Generated by Django 5.0.3 on 2024-03-23 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelers', '0003_states'),
    ]

    operations = [
        migrations.CreateModel(
            name='the_city',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=30)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travelers.states')),
            ],
            options={
                'db_table': 'the_city',
            },
        ),
    ]
