# Generated by Django 5.0.3 on 2024-03-23 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelers', '0004_the_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='destinations/')),
                ('day1_name', models.TextField()),
                ('day1_description', models.TextField()),
                ('image1', models.ImageField(upload_to='packages/')),
                ('day2_name', models.TextField()),
                ('day2_description', models.TextField()),
                ('image2', models.ImageField(upload_to='packages/')),
                ('day3_name', models.TextField()),
                ('day3_description', models.TextField()),
                ('image3', models.ImageField(upload_to='packages/')),
                ('day4_name', models.TextField()),
                ('day4_description', models.TextField()),
                ('image4', models.ImageField(upload_to='packages/')),
                ('day5_name', models.TextField()),
                ('day5_description', models.TextField()),
                ('image5', models.ImageField(upload_to='packages/')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travelers.the_city')),
            ],
        ),
    ]
