# Generated by Django 5.0.3 on 2024-03-23 10:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelers', '0005_package'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('image1', models.ImageField(upload_to='hotels/')),
                ('image2', models.ImageField(upload_to='hotels/')),
                ('image3', models.ImageField(upload_to='hotels/')),
                ('image4', models.ImageField(upload_to='hotels/')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travelers.the_city')),
            ],
        ),
    ]
