# Generated by Django 5.0.3 on 2024-03-23 10:37

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelers', '0007_room'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_date', models.DateField(default=django.utils.timezone.now)),
                ('check_out_date', models.DateField(default=django.utils.timezone.now)),
                ('no_of_guests', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, default='1000', max_digits=8)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travelers.room')),
            ],
        ),
    ]
