# Generated by Django 5.0.3 on 2024-03-29 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelers', '0008_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='Airlines',
            fields=[
                ('airline_id', models.AutoField(primary_key=True, serialize=False)),
                ('airline_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Airline',
            },
        ),
        migrations.CreateModel(
            name='Airports',
            fields=[
                ('airport_name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('city', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Airports',
            },
        ),
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'login',
            },
        ),
        migrations.CreateModel(
            name='Flights',
            fields=[
                ('flight_id', models.AutoField(primary_key=True, serialize=False)),
                ('departure_time', models.DateTimeField()),
                ('arrival_time', models.DateTimeField()),
                ('duration_minutes', models.IntegerField()),
                ('fare', models.DecimalField(decimal_places=2, max_digits=10)),
                ('airline_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travelers.airlines')),
                ('arrival_airport_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrivals', to='travelers.airports')),
                ('departure_airport_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departures', to='travelers.airports')),
            ],
            options={
                'db_table': 'Flights',
            },
        ),
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('booking_id', models.IntegerField(primary_key=True, serialize=False)),
                ('fullname', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('payment_method', models.CharField(max_length=50)),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travelers.flights')),
            ],
            options={
                'db_table': 'Bookings',
            },
        ),
    ]
