# Generated by Django 5.0.3 on 2024-03-30 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelers', '0009_airlines_airports_login_flights_bookings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='booking_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
