# Generated by Django 6.0.6 on 2026-06-24 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelers', '0010_alter_bookings_booking_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookings',
            name='flight',
        ),
        migrations.AddField(
            model_name='bookings',
            name='flight_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
